volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  monitoring-network:
    external: true
  db-network:
    external: true

services:
  telegraf:
    image: docker.io/telegraf:latest
    restart: always
    container_name: telegraf
    hostname: telegraf
    networks:
      - monitoring-network
    volumes:
      - /volume3/docker-compose/monitoringobservability/telegraf/mibs/:/usr/share/snmp/mibs/
      - /volume3/docker-compose/monitoringobservability/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9126:9126
    command: telegraf --config /etc/telegraf/telegraf.conf

  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    command: 
      --config.file=/etc/prometheus/prometheus.yml
      --storage.tsdb.path=/etc/prometheus/data
    networks:
      - monitoring-network
    restart: always
    ports:
      - 9090:9090
    volumes:
      - /volume3/docker-compose/monitoringobservability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /volume3/docker-compose/monitoringobservability/prometheus/targets/prometheus.json:/etc/prometheus/targets/prometheus.json
      - /volume3/docker-compose/monitoringobservability/prometheus/targets/grafana.json:/etc/prometheus/targets/grafana.json
  grafana:
    image: docker.io/grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    networks:

      - monitoring-network
    restart: always
    depends_on:
      - prometheus
    ports:
      - 3001:3000
    # entrypoint:
    #   - sh
    #   - -euc
    #   - |
    #     mkdir -p /etc/grafana/provisioning/datasources
    #     cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
    #     apiVersion: 1
    #     datasources:
    #     - name: Loki
    #       type: loki
    #       access: proxy 
    #       orgId: 1
    #       url: http://loki:3100
    #       basicAuth: false
    #       isDefault: true
    #       version: 1
    #       editable: false
    #     EOF
    #     /run.sh
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana_data:/var/lib/grafana
      - /volume3/docker-compose/monitoringobservability/grafana/provisioning/:/etc/grafana/provisioning/
  
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring-network
  
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitoring-network
  
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    networks:
      - monitoring-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300
  
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    environment:
      TZ: America/New_York
      DOZZLE_ENABLE_ACTIONS: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8888:8080
    networks:
      - monitoring-network
  
  autoheal:
    container_name: autoheal
    image: willfarrell/autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - monitoring-network
    environment:
      AUTOHEAL_CONTAINER_LABEL: all

  speedtest-tracker:
    image: ghcr.io/linuxserver/speedtest-tracker:latest
    container_name: SpeedTest-TRACKER
    healthcheck:
     test: curl -f http://localhost:80/ || exit 1
    environment:
       PUID: 0
       PGID: 0
       APP_TIMEZONE: America/New_York
       DISPLAY_TIMEZONE: America/New_York
       APP_KEY: base64:Mk3oIhBicQx5NuTYpKcqNSRt4ANv+3nikg+z9yzWYrI= #docker exec speedtest-tracker php /app/www/artisan key:generate --show
       DB_CONNECTION: pgsql
       DB_HOST: shared-database-db-1
       DB_PORT: 5432
       DB_DATABASE: speedtest
       DB_USERNAME: schergr
       DB_PASSWORD: Zachchelsea1986!
       SPEEDTEST_SCHEDULE: 4 */1 * * *
       SPEEDTEST_SERVERS: 51306, 12563, 53403, 31407, 9125
    volumes:
      - /volume3/docker-compose/speedtest/config:/config:rw
    ports:
      - 8999:80
    restart: on-failure:5
    networks:
      - monitoring-network
      - db-network