global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  # - "first.rules"
  #   # - "second.rules"
  #
scrape_configs:
  - job_name: telegraf
    metrics_path: /metrics
    static_configs:
      - targets:
          - telegraf:9126
  - job_name: json_exporter
    metrics_path: /metrics
    static_configs:
      - targets:
          - json-metric-exporter:5000
